mpirun -np 32 ./ex_k4 \
	-ts_type cn \
	-ksp_type fgmres \
	-pc_type fieldsplit -pc_fieldsplit_type multiplicative \
	-fieldsplit_a_pc_type gamg -fieldsplit_a_pc_gamg_type agg \
	-fieldsplit_a_mg_levels_ksp_type gmres -fieldsplit_a_mg_levels_pc_type jacobi \
	-fieldsplit_a_pc_gamg_threshold 0 -fieldsplit_a_pc_gamg_square_graph 10 \
	-fieldsplit_a_pc_gamg_reuse_interpolation true \
	-fieldsplit_b_pc_type gamg -fieldsplit_b_pc_gamg_type agg \
	-fieldsplit_b_mg_levels_ksp_type gmres -fieldsplit_b_mg_levels_pc_type jacobi \
	-fieldsplit_b_pc_gamg_threshold 0 -fieldsplit_b_pc_gamg_square_graph 10 \
	-fieldsplit_b_pc_gamg_reuse_interpolation true \
	-ts_monitor -ksp_monitor -log_view
